### ISSUE TITLE
Please add nodejs & reactjs to allowed software.

### ISSUE THREAD

**Issue by RDS5** [Aceyware/Aceyware#1]
These libraries aide new developers create high quality programs in little time using their various functions.
Unlike C/C++, these languages are memory safe & very cross platform as they run in V8's JIT. https://v8.dev/blog/sandbox
React and node are both fully opensource libraries that are widely used by many developers like myself, and it'd be a shame to reject one of the largest development communities over this.

Cross-platform native interfaces are possible using things like Github's Electron, as seen with Discord.
Creating fast, native and cross platform apps with little cost to the developer. https://discord.com/blog/android-react-native-framework-update

Codebase efficiency can also be greatly improved with tools like Facebook's superpack, to reduce developer-induced code-size increases. https://engineering.fb.com/2021/09/13/android/superpack/

**Comment by PEPSIMANTR** [comment]
FUCK OFF
